### PR TITLE
Require path separator before shortcuts and ignore all stat errors.

### PR DESCRIPTION
**Pull request by Osmose**
I'm also going to handle the drive letter issues but want to get a PR up to test AppVeyor.

### CODE REVIEW

**Comment by Osmose** [comment]
I have no idea why AppVeyor is failing the build, it says all the tests passed. @Trudko, do the tests on this branch work locally for you?

**Comment by Osmose** [comment]
Looks like the build failure is due to https://github.com/atom/atom/issues/9277. I'll just have to watch the test output to see whether the tests actually fail or not. Oh well!

**Comment by Trudko** [comment]
@Osmose what tests  ? :)

**Comment by Osmose** [comment]
> @Osmose what tests ? :)

Oh man am I missing a joke or am I being unclear aaaahhhhhhhh

**Pull request merged**
