### PR TITLE
Move to the top and to the bottom of file list without React

### LINKED ISSUE #120: Page Up and Page Down keys for navigation in list
Enable Page Up and Page Down keys for navigation in list, please 😇

### PR DESCRIPTION
**Pull request by AlexWayfer**
Still trying to close #120 :)

### CODE REVIEW

**Comment by AlexWayfer** [comment]
Oh, test failed not at lines that I edited…

**Comment by Osmose** [comment]
The released version is failing that test too: https://ci.appveyor.com/project/Osmose/advanced-open-file/build/95

No idea why, but I think it's safe to consider your test as passing.

**Comment by Osmose** [comment]
This looks good to me, nice work!

It's missing a mention of the shortcuts in the README, and the addition of your name to the AUTHORS file, but I can add those myself. :D

**Comment by AlexWayfer** [comment]
My English is bad, so I think if you'll describe shortcuts it will be better for everybody :)
Authors — as you want.

**Comment by Osmose** [comment]
Just released this as 0.16.4, should be available to everyone now. Thanks again, great patch!

**Pull request merged**
