### PR TITLE
Fix #13: Fix Windows path handling.

### LINKED ISSUE #13: Issue listing files on windows
Hi, If I'm on windows I have troubles listing the file content of the current directory. It looks like it's related to the windows style paths. For example:

C:\Projects\TestProject will list nothing, where \Projects\TestProject will show all directories..

### PR DESCRIPTION
**Pull request by Osmose**
Also removes support for creating multiple files at once; refactoring
the code to support Windows paths created some bugs that involved fixing
the multiple-file code, which I didn't think we needed anyway.

@NuclearCookie Would you be able to pull down this branch and test it to see if it works on your Windows machine? I don't have one set up to test this easily and I'd rather make sure I fixed your specific problem anyway. :D

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Hey! Thanks for looking in to this. It's better already. I can see all paths and files in the directories and I can switch. I cannot open the files yet however.. Is it possible you still use the old path to select the file to open? It now opens a new "untitled" document..

**Comment by Osmose** [comment]
Hmmm, nothing is jumping out at me as the problem... I'll try to get this running on a Windows machine sometime this weekend and see if I can replicate the issue.

**Comment by Osmose** [comment]
> Hey! Thanks for looking in to this. It's better already. I can see all paths and files in the directories and I can switch. I cannot open the files yet however.. Is it possible you still use the old path to select the file to open? It now opens a new "untitled" document..

I tried this out on a Windows 7 machine available to me and didn't have this issue. Which version of Windows are you using, and what paths are you trying?

I did run into an issue with listing files in a directory with a space in it, but that led to an error message, not the symptoms you're describing.

**Comment by Osmose** [comment]
@Traverse mentioned that this fixed their issues on Windows, so I'm going to merge it. We can discuss whether you're still experiencing these issues in #13. Thanks for the help!

**Pull request merged**
