### PR TITLE
Fix #4: Handle directories named ~.

### LINKED ISSUE #4: Can't enter directories named ~
The fix in #3 broke our ability to enter directories named `~`. I mean you shouldn't do that but oops.

### PR DESCRIPTION
**Pull request by Osmose**
I'm pretty sure a bug in some other code created the directory that led to me finding this bug, but whatevs.

### CODE REVIEW

**Comment by Osmose** [comment]
@mythmon How willing are you to do code reviews for this? :P

**Comment by mythmon** [comment]
I'm a little fuzzy on how this addon works internally (I never got around to trying to add that feature I talked about). One thing that seems weird is that you are using the catch block of the try/catch as the normal case instead of the exceptional case. What about [`fs.exists`](https://nodejs.org/api/fs.html#fs_fs_existssync_path)?

**Comment by Osmose** [comment]
> What about fs.exists?

The docs say it's going to be deprecated and everything on Google says to use stat instead. Otherwise I'd love to use exists. Maybe I should just not care?

**Comment by mythmon** [comment]
Huh, I totally missed that. Yeah, probably best not to use pre-deprecated stuff. Given that, this looks fine. Weird, but I can't think of a better way to do it.

**Pull request merged**
